[package]
name    = "pkt-rs"
version = "0.1.0"
authors = ["Eishun Kondoh <dreamdiagnosis@gmail.com>"]
edition = "2018"

[dependencies]
nom       = "5"
byteorder = "1.3.2"
libc      = "0.2.66"
eui48     = "0.4.6"
